### ISSUE TITLE
abyss-pe: create abyss-map index files by default  

### ISSUE THREAD

**Issue by benvvalk** [bcgsc/abyss#107]
`abyss-pe` should create abyss-map index files by default, rather than building the indexes in memory and then throwing them away afterwards.   This would speed up assemblies with multiple PET/MPET libraries, as commented here: https://www.biostars.org/p/165687/#187648.

**Comment by benvvalk** [comment]
The only downside I can see is that it would cause abyss-pe runs with the -j option (multithreading option for GNU make) to fail, because parallel processes would try to write the index file at the same time.

**Comment by sjackman** [comment]
How long does it take to index a human assembly? There's an I/O advantage to not writing the index to disk, if possible. If there's only one library, the index should not be written to disk.

> The only downside I can see is that it would cause abyss-pe runs with the -j option (multithreading option for GNU make) to fail, because parallel processes would try to write the index file at the same time.

This issue can be fixed by adding the FM-index as a rule and dependency to the Makefile created by `abyss-index`, rather than as a by-product of `abyss-map`.

**Comment by benvvalk** [comment]
Oh, right -- duh! (separate rule for FM-index file)

Good point also about making a special case for single-library contiging/scaffolding.

**Comment by lsterck** [comment]
Hi Ben, Shaun,

Just some additional info: it apparently took nearly 3 hours to build the index on my unitigs file :-/ while the mapping step (without index building) takes an hour or 4. So this is substantial I would say. This of course only starts to be beneficial when multiple libraries have to be mapped! Coming to think of it: the best would probably be to build it once in memory and keep it there for all mappings (if that is even possible?)
Can I add in an additional question? : The size of the index seems to be bigger than the input unitigs file, how can that be?

**Comment by sjackman** [comment]
The index should be something like 25% bigger than the input unitigs file. It is an uncompressed FM-index using as I recall 10 bits per input byte of the unitigs.

**Comment by sjackman** [comment]
To build the index takes 10 *bytes* (not bits) of RAM per input byte. How big is the unitigs file, and how much RAM does your machine have?

**Comment by lsterck** [comment]
Hi Shaun,

my unitigs file is approx 27GB and the FM index file is ~30GB (so that kinda fits with your calculation). I'm running the analysis on a shared memory cluster system on which I can get up to 14TB of RAM (a single node has 250GB RAM though). Neither storage nor memory is really an issue for the moment but I would be interested in speeding up the analysis ;-) .

**Comment by sjackman** [comment]
A 27 GB unitigs file would take ~270 GB of RAM to index, which is slightly more than the 250 GB available per node, so memory thrashing may have been a mild issue. I'm not entirely clear about the memory architecture of your system, but it sounds like that additional 20 GB of RAM would have been located on a second machine and transferred over the network. I'd be curious to know if a unitigs file smaller than 25 GB indexes significantly faster on your system.

**Comment by sjackman** [comment]
`abyss-index --bwt2fm` is able to take a Burrows Wheeler Transform (BWT) created by an external program and use it to create the FM-Index. Much research has been done in recent years (although I'm not really up to date on it) on parallel and disk-based BWT. For indexing the 20 Gbp white spruce genome we used [bwtdisk](http://people.unipmn.it/manzini/bwtdisk/) because we did not have a 200 GB RAM machine at the time.

**Comment by lsterck** [comment]
OK, I was a little confused where this was going to but I understand now.
To be complete I actually built the index on another server with 500GB RAM and the time it needed I reported before was from running it on that server (apologies for the misinformation). On the shared memory cluster I am however able to build it in memory and that seems to work fine (as does the first step in the whole process which takes ~4TB of RAM). I'm no expert in all this but this is what I get from the tech spec of the cluster: 
> the blades are connected through a SGI-proprietary NUMAlink6 interconnect. The interconnect also offers support for global address spaces across shared memory partitions and offload of some MPI functions.
As far as I can estimate it it does seems to take longer on the shared memory system to build the same index so the 'issue' you mention might have some effect indeed.
