### ISSUE TITLE
ABySS does not improve contig nor scaffolds stats

### ISSUE THREAD

**Issue by lsterck** [bcgsc/abyss#117]
I'm running a fairly large assembly process for which I have a few dozen input fastq files. I run this on a high memory cluster system, at least for the initial unitig building stage. However to improve efficiency ( and to reduce my cluster runtime costs ;-) ) I stop the abyss-pe script after the unitig file has been written and before it starts aligning the paired-end data to the unitgs to create the contigs. Instead of letting the initial abyss-pe script do the mapping I do these myself (on a different, read cheaper cluster) based on the cmdlines I can get when doing a dry-run of the abyss pipeline. Once all the result files from the mapping stap are generated I restart the abyss-pe script and it picks up where it left off and starts to generate the contig file. I do the same at the mapping stage step for the scaffolds. This seems to work fine from a technical point of view, as in: it does not give any error(s) and all expected files are present in the end. However after inspecting the unitig, contigs and scaffolds files it turns out that these are largely identical (with a few sequences less after each step) but the general assembly result stats remain the same as for the initial unitig file.
I'm now wondering if I'm missing something somewhere? Does ABySS for instance keeps data/info in memory that I'm loosing by stopping and restarting the script?

For completeness, this issue relates to a question I posed on Biostars: [https://www.biostars.org/p/185516/](https://www.biostars.org/p/185516/)

any help is highly appreciated.

**Comment by benvvalk** [comment]
Hi Lieven,

In principle what you are doing is fine, but I suspect that there is something going wrong during the hand-off between the unitig and contig stages.  It sounds like you are manually stopping the assembly job at the unitig stage which might cause trouble with partially generated output files.  Instead, you can add the word `unitigs` to the end of your `abyss-pe` command and it will stop cleanly after the unitig stage.  Then for your second contig/scaffold job, just remove the `unitigs` from the end of your `abyss-pe` command and it will resume where it left off (contig stage).

If possible, I would recommend doing at least one full `abyss-pe` run on the same machine, just to clarify if the problem is with your `abyss-pe` parameters or if it is with the stopping/resuming business.

If you need further help debugging, you will have to provide your `abyss-pe` command(s) and the corresponding log output(s).  (If possible, please add `v=-v` to your `abyss-pe` command to enable verbose logging.)

**Comment by lsterck** [comment]
Hi Ben,

thanks for the swift reply! That's excellent I'll immediately give that 'unitigs' option a try.
Building on the same 'principle' can I add 'contigs' to the cmdline such that it will cleanly stop after the contig building stage (before doing scaffolding)?
I guess that when I manually stop the abyss-pe process when it starts doing (or is already busy) with the mapping , these potential partial output should not be a problem or will it?
Before the mapping I also do build the index files separately and keep them on disk to be re-used, but that can also not be the problem I think.

**Comment by benvvalk** [comment]
Hi @lsterck:

No problem, you're welcome.   Yes, there are similar targets for 'contigs' and 'scaffolds' as well.  I am not sure, but I think stopping the assembly part way during mapping could create partial output files, which would then (erroneously) treated as complete when you resume the assembly at the contig stage.  I am thinking in particular of the *.hist and *.dist files.

**Comment by lsterck** [comment]
Hi Ben,

great, good to know!
So I just add these 'targets' at the very end of the abyss-pe cmdline (so even after the input files)?
cheers,
lieven

**Comment by sjackman** [comment]
That's right. `abyss-pe` is a Makefile script, so the command line syntax is the same as `make`. There's also a `scaftigs` target (break all scaffolds at Ns).

**Comment by lsterck** [comment]
Great, good to know!
Just out of curiosity: what is the difference between those scaftigs and the regular contigs?
thx.

**Comment by benvvalk** [comment]
@lsterck: Where sequence identity is high enough (90% by default), ABySS will collapse paths through the scaffold graph into a consensus sequence (see `PathConsensus` step for -7.fa in `abyss-pe` file).  Other than that, I don't think there is much different between contigs and scaftigs.

**Comment by lsterck** [comment]
Hi Ben, Shaun,

apologies for taking so long to get back on this topic (have been seriously side-tracked past year :-/ ). Anyway I have a couple of remaining questions concerning this topic here.
The use of these targets indeed seems to work smoothly (from a technical point then). I had the opportunity to compare a run using these targets and one with the targets and they do largely end up in the same result. However, not exactly the same result ???? the difference is minor, as in just a couple of contigs/unitgs less or more on a few million but still. Is there any logical explanation for this difference? 
80.73e6 8953164 2296185 8953164 500     500     762     1386    2673    1836    26448   10.71e9 k80_2/ppinTk80_2-contigs.fa
80.73e6 8952982 2296165 8952982 500     500     762     1386    2673    1836    26448   10.71e9 k80_2/ppinTk80_2-unitigs.fa
80.73e6 8953158 2296185 8953158 500     500     762     1386    2673    1836    26448   10.71e9 k80/ppinTk80-contigs.fa
80.73e6 8952976 2296165 8952976 500     500     762     1386    2673    1836    26448   10.71e9 k80/ppinTk80-unitigs.fa
In the above result the "_2" results are from a run not using the 'unitig' target, while the other one is with using the unitig target first and then re-start up to contig.

thx in advance

**Comment by sjackman** [comment]
Restarting the assembly shouldn't be the cause of the difference. I'd suspect something else. Did the installed version of ABySS change between the two runs? Did the number MPI parameters `np` change? Please report the exact command line used in both cases.

**Comment by benvvalk** [comment]
Thanks @sjackman.

@lsterck Yes, we do work pretty hard to maintain reproducible output in ABySS, but perfection is hard to achieve (especially in the context of multi-threaded programs).

Have you tried a duplicate run for either of your two assembly methods? Or is it too expensive/time-consuming to re-run the assembly?  It would be very helpful to know if the variability happens between duplicate runs with the same assembly procedure, or whether it is somehow caused by the difference in your two assembly procedures.

Another idea would be to run `abyss-fac` on the different stages of the assembly (-1.fa, -2.fa, -3.fa) to see which assembly stage introduces the differences.

Based on your `n:500` column, it looks like there are 6 sequences that are different between the two assemblies, and that the differences are introduced prior to the unitig stage (-3.fa).

I suppose it really depends on your application whether such a small amount of variability is a concern (e.g. clinical applications).  In most contexts, I would not be very concerned.

**Comment by lsterck** [comment]
thanks for the swift reply both.

@sjackman : 
I checked and indeed, the k80 was run on 40 cores and the k80_2 on 50 . That might indeed explain the minor difference. thx and apologies for not spotting this.
@benvvalk : 
OK, yes that might learn us something, I'll keep that in mind but first will have to see if I can spare the resources/time for it.
That I can do, I started the analysis and will post the result as soon as I have them.
Ah, and to reassure you, I'm indeed not worried at all about this very minor difference . I'm very much worried though about an issue I posted on biostars months ago ( https://www.biostars.org/p/185516/ ) . But I will not go into that one in this thread to keep it on topic ;-)

**Comment by sjackman** [comment]
The number of MPI processes is known to affect the bubble popping stage of ABYSS-P in minor ways. That likely accounts for the difference.

**Comment by sjackman** [comment]
I commented at https://www.biostars.org/p/185516/

**Comment by lsterck** [comment]
@benvvalk 
here are the abyss-fac stats for the -1 -2 -3 . fa files .
```
n       n:500   L50     LG50    NG50    min     N80     N50     N20     E-size  max     sum     name
160.1e6 9281986 2511295 9281986 500     500     727     1259    2350    1639    26448   10.4e9  k80_2/ppinTk80_2-1.fa
83.08e6 9281986 2511295 9281986 500     500     727     1259    2350    1639    26448   10.4e9  k80_2/ppinTk80_2-2.fa
80.73e6 8952982 2296165 8952982 500     500     762     1386    2673    1836    26448   10.71e9 k80_2/ppinTk80_2-3.fa
160.1e6 9281986 2511295 9281986 500     500     727     1259    2350    1639    26448   10.4e9  k80/ppinTk80-1.fa
83.08e6 9281986 2511295 9281986 500     500     727     1259    2350    1639    26448   10.4e9  k80/ppinTk80-2.fa
80.73e6 8952976 2296165 8952976 500     500     762     1386    2673    1836    26448   10.71e9 k80/ppinTk80-3.fa
```
as far as I can see the 'difference' appears between -2 and -3 which would then coincide with shaun's answer that it's likely the bubble popping stage, no?

**Comment by sjackman** [comment]
I meant the bubble popping stage of `ABYSS-P` in the 1st stage. But yeah, it looks like `PopBubbles` may have the same issue. If you want to test it, I'd be curious to know if PopBubbles produces the same results from run to run with the same parameters, or if you change the number of threads with `-j`.
