### ISSUE TITLE
Input Data about Abyss-sealer 

### ISSUE THREAD

**Issue by bioinfomaticsCSU** [bcgsc/abyss#136]
When running abyss-sealer, I have a question:
"abyss-sealer -b20G -k90 -k80 -k70 -k60 -k50 -k40 -k30 -o test -S scaffold.fa read1.fa read2.fa" 
Does "read1.fa" keep the left reads of a library? Or is "read1.fa" a single-end read file?

**Comment by benvvalk** [comment]
Hi @bioinfomaticsCSU,

In this example `read1.fa` are the left reads and `read2.fa` are the right reads.  It actually doesn't matter what you give the read files, because Sealer does not use any of the pairing information.  It just extracts k-mers from the reads to build the de Bruijn graph.  The reads are also allowed to be FASTQ format, which is the more commonly used than FASTA for input reads files.   The input reads files may also be gzipped.

**Comment by bioinfomaticsCSU** [comment]
Thanks very much!

**Comment by aersoares81** [comment]
A follow up to this question: Can/should we use more than one library?

**Comment by benvvalk** [comment]
Hi Andre,

I would say yes, you should use all the libraries.  It will improve your sequencing coverage and could close gaps in the de Bruijn graph.  Since Sealer doesn't use the pairing information or fragment sizes, it doesn't matter if you mix all the paired-end data together in a single run. (That is how we usually run Sealer.)

I would like to note here that Sealer has a known issue with stalling on smaller k values (roughly speaking, k < 60): https://github.com/bcgsc/abyss/issues/79.  So I would advise not going below k=60.

**Comment by aersoares81** [comment]
Hi, thanks! I guess I should cat all the fastq files into a single one then, I didn't see anything in the docs saying it's ok to add more than 2 files to the command line.

Thanks for the heads up!

**Comment by benvvalk** [comment]
Yes, Sealer does support an arbitrary number of FASTA/FASTQ arguments, so you don't need to concat them beforehand.  Just include all the files as arguments (in any order).

**Comment by sjackman** [comment]
```
abyss-sealer --help
Usage: abyss-sealer-b <Bloom filter size> -k <kmer size> -k <kmer size>... -o <output_prefix> -S <path to scaffold file> [options]... <reads1> [reads2]...
```

The ellipsis `...` indicates that you may include multiple files. It's a convention, but if you're not familiar with it, I can see that it wouldn't be clear.

**Comment by aersoares81** [comment]
Thank you guys, I totally missed out the ellipsis and its meaning. 😳

**Comment by sjackman** [comment]
No worries at all. Happy to help.
