### ISSUE TITLE
N in abyss assembler

### ISSUE THREAD

**Issue by woodoo46** [bcgsc/abyss#141]
Hi there,

Why some of the Abyss contigs have N in them? Do they mean ambiguous bases or gap?

Thanks.

**Comment by benvvalk** [comment]
Hi @woodoo46,

A single N indicates a case where the read pair distances indicated an overlap between two sequences, but the overlapping ends were not merged because the sequences did not exactly match.  I don't recall if the single N character is output as uppercase (`N`) or lowercase (`n`) in that case.

A sequence of two or more N's is the result of consensus calling, I believe.  This happens when collapsing multiple paths with high sequence identity that connect two endpoints.

**Comment by sjackman** [comment]
> I don't recall if the single N character is output as uppercase (N) or lowercase (n) in that case.

A single lower-case `n` indicates that the two sequences are expected to overlap, but a perfect overlap was not found.

A sequence of capital Ns indicates a gap, either a gap in sequencing coverage, or a scaffolding gap over an unresolved repeat.

Ambiguous bases are represented by IUPAC ambiguity codes, usually not `N`, although that's technically possible if reads showed evidence for all four bases at one position.
