### ISSUE TITLE
Problems of openmpi in abyss

### ISSUE THREAD

**Issue by zhanglu295** [bcgsc/abyss#155]
Hi there, 

I have two questions when I used abyss for de novo assembly.

1.  The program was usually deadlocked at “Finding adjacent k-mer…” when I used the command:

mpirun -np 10 ABYSS-P -k70 -q15 -v   --coverage-hist=coverage.hist -s config1-bubbles.fa  -o config1-1.fa new.fastq 

I have read the users FAQ and added "--mca btl_sm_eager_limit 16000 --mca btl_openib_eager_limit 16000”, but it cannot solve the problem?

I compiled abyss use --enable-maxk=256, shall I reduce the value of --enable-maxk to avoid this problem?

2. I also tried to set -np 1, but another error was reported, "mpirun noticed that process rank 0 with PID 151501 on node sh-112-02 exited on signal 11 (Segmentation fault).” Any thought of this problem?

Thanks,
Eric

**Comment by sjackman** [comment]
Do try a smaller value of `maxk`, such as `--enable-maxk=96`.
Are you able to monitor the memory usage on the machines? ABySS reports how much memory it's using as it loads sequences. Are you close to the limit?
`np=1` depending on your sequencing data set will almost certainly exceed the memory available of a single process.
Try using the new ABySS 2.0 memory-efficient Bloom filter data structure instead of using MPI. Ben @benvvalk can give you instructions on that.

**Comment by benvvalk** [comment]
I agree with Shaun's comment about trying `--enable-maxk=96`.  It would be useful diagnostic info.  And also with Shaun's guess that you are probably running out of memory with `-np 1`.

Using `ntcard` to count distinct k-mers is a good suggestion, and also very helpful diagnostic info.

If you are interested in trying the new Bloom filter assembly mode, there are instructions here: https://github.com/bcgsc/abyss#assembling-using-a-bloom-filter-de-bruijn-graph.
