### ISSUE TITLE
Release ABySS 2.0.3

### ISSUE THREAD

**Issue by sjackman** [bcgsc/abyss#172]
I'd like to tag a point release of ABySS to address a bug in `abyss-samtobreak` reported here https://github.com/bcgsc/abyss-2.0-giab/issues/2

I'm some one or two other `abyss-samtobreak` not-yet-implemented features that I'd like to get into this release, namely a TSV output format.

**Comment by benvvalk** [comment]
Sure. I've been wanting to make 2.0.3 release for quite some time now.

For 2.0.3, the main change would be some important bug fixes to `abyss-bloom-dbg`, which have already been tested.

Beyond that, my only TODOs are settling on the new default sparsehash size value (#171) and fixing the outstanding compiler errors.

**Comment by benvvalk** [comment]
Yes, this is something I still need to do, for more than a month now.

I've been unsuccessful in reproducing the CI errors with clang on Ubuntu 14 (laptop) and Ubuntu 16 (home computer), even though the CI environment is supposed Ubuntu 14.  My next idea is to enable verbose output for Google test, which might give me some clues about what is going wrong.

There is a different set of subset unit tests on Mac that are also currently failing.  It would really be very helpful to have access to a Mac with root access so that I can use `gdb` and `valgrind`.  Maybe our group laptop would fit the bill for that.

**Comment by sjackman** [comment]
You can ssh into CircleCI's machines. I don't think we're currently using CircleCI for ABySS. I could set it up if you'd find it helpful.

**Comment by benvvalk** [comment]
@sjackman I didn't know that.  Yes, if CircleCI can run the tests with clang and produces the same error, being able to ssh in would be extremely helpful.

**Comment by sjackman** [comment]
Who knows whether it'll produce the same error, if it's not reproducible by you on the two Ubuntu machines that you've tried so far, but we can try. CircleCI let's you pick which Docker image you run your tests on, so its results should be easily reproducible locally with Docker.

**Comment by benvvalk** [comment]
Cool. I'll look into that (reproducing the errors on CircleCI), if you don't get around to it yourself.

**Comment by sjackman** [comment]
Here's a PR to migrate from CircleCI 1.0 to CircleCI 2.0: https://github.com/bcgsc/abyss/pull/194

**Comment by sjackman** [comment]
I've reproduced two of the 12 TravisCI test failures with CircleCI and clang 3.8 over at PR https://github.com/bcgsc/abyss/pull/197

**Comment by benvvalk** [comment]
@sjackman I do appreciate your help with this.  I'm planning to work on it tomorrow afternoon, after the assembly meeting.

**Comment by benvvalk** [comment]
still working on it

**Comment by benvvalk** [comment]
I disabled the Travis clang tests, as of commit 442c8494aa117cbb149596324230c77d83c2f00a:

**Comment by benvvalk** [comment]
The CircleCI clang failures are legit and are still unsolved.

I will do an interim release anyway and try to fix the clang issues in the next minor release.  Not only because Inanc needs a release this week, but also because the current development HEAD corresponds to closely to one of our assemblies.

**Comment by sjackman** [comment]
Yeah for a release!

**Comment by sjackman** [comment]
ABySS 2.0.3 was released https://github.com/bcgsc/abyss/releases/tag/2.0.3
