### ISSUE TITLE
Error: Assertion 'cout.good()' failed

### ISSUE THREAD

**Issue by AMMMachado** [bcgsc/abyss#214]
Hi, 

I'm trying  to optimize the abyss parameters with bloom filter to  230 M PE illumina reads with 150bp . 
I'm running the program in a cluster with 40 cpus and 420 GB memory. 
With k61 the program runned without problems.. But wiht 71 give me this error.
Other question, if i increase the k should i decrease the bloom filter memory ? Which criteria should i use to choose the parameters of kc , H and B ? 

Can be out of memory ?

Command:

abyss-pe -C X_3st_Assembly name=X_k71 B=325G H=4 kc=3 v=-vv np=38 k=71 lib="pe1" pe1='XAB_1.fastq.gz XAB_2.fastq.gz' 1>X.log 2>A.err &

ERROR:

Reading `X_k71-1.fa'...
Finding overlaps of exactly k-1 bp...
V=29057602 E=36360225 E/V=1.25
Degree: _█▃
        01234
0: 7.9% 1: 62% 2-4: 31% 5+: 0% max: 4
Finding overlaps of fewer than k-1 bp...
V=29057602 E=3007435086 E/V=103
Degree:  █▃
        01234
0: 3.7% 1: 62% 2-4: 31% 5+: 2.5% max: 118261
AdjList: AdjList.cpp:401: int main(int, char**): Assertion `cout.good()' failed.
bash: line 1: 21726 Aborted                 (core dumped) AdjList -vv -k71 -m50 --dot X_k71-1.fa > X_k71-1.dot
make: *** [X_k71-1.dot] Error 134
make: *** Deleting file `X_k71-1.dot'

If possible, can you give me some advices to optimize the parameters.

Thanks in advance.
AMachado

**Comment by benvvalk** [comment]
What is your approximate genome size?

The `Assertion cout.good()' failed.` part indicates that there was an IO error when writing the output file to disk.  Usually this is either because you ran out of disk space, or you don't have write permissions, or there was some other file system related error.  The Bloom filter assembly mode currently has an issue where it tends to generate very large graph files at the `AdjList` step.

For Bloom filter parameters, I usually try a few different values of `kc`.  In my experience, `kc=3` or `kc=4` usually work best.  `B` and `H` don't matter as much, as long as the false positive rate (reported in the log if `abyss-pe v=-v` is used) is below 10% or so.

**Comment by AMMMachado** [comment]
Hey ben, 

Thanks for the quick response.
I already talked to the system administrator and we have already increased the available disk space.  
There are any minimum requirement in terms of disk space for each assembly, and with different k? i mean, we had about 150GB now we have + - 300GB, it's enough ?
Our organism is a fish, the genome size has + - 1GB and is a bit heterozygous.
At this moment i tried the abyss (assembly+scaffolding) and Abyss+soapdenovo (assembly (abyss) and scaffolding (soapdenovo). For the contigs the abyss performed much  better than soap with a very good contiguity. But in scaffolding i obtained better results with soap. There are some parameters to change in abyss to improve the scaffolding? 

Thank you again for the help.

**Comment by AMMMachado** [comment]
Hi Ben, 

I tried solve the problem, increasing the disk space from 150 to 600GB, however the program give me the same error. 

make: Entering directory `X_3st_Assembly'
Reading `X_k71-1.fa'...
Finding overlaps of exactly k-1 bp...
V=29057602 E=36360225 E/V=1.25
Degree: _█▃
        01234
0: 7.9% 1: 62% 2-4: 31% 5+: 0% max: 4
Finding overlaps of fewer than k-1 bp...
V=29057602 E=3007435086 E/V=103
Degree:  █▃
        01234
0: 3.7% 1: 62% 2-4: 31% 5+: 2.5% max: 118261
AdjList: AdjList.cpp:401: int main(int, char**): Assertion `cout.good()' failed.
bash: line 1: 26321 Aborted                 (core dumped) AdjList -vv -k71 -m50 --dot X_k71-1.fa > X_k71-1.dot
make: *** [X_k71-1.dot] Error 134
make: *** Deleting file `X_k71-1.dot'

I also tried with kmer 44 , beyond the 61 already tested and also runned without problems.. Seems a problem with high kmer valeus. 
Should i decrease the memory valeu or increase more the disk space ? 

Thank you again for the help.

**Comment by benvvalk** [comment]
Bummer.

I just noticed in your log output above that the number of edges created by < k-1 bp overlaps is 3,007,435,086.  That is enormous! (That is probably the root cause of the large graph file problem.)

As a workaround, perhaps add `m=$k-1` to your abyss-pe command, where `$k` is whatever k-mer size you are assembling with.  That will tell `AdjList` not to identify < k-1 bp overlaps and create edges for them.  It will probably lessen the quality of your assembly, but at least the assembly would run to completion (hopefully).

For best results, your best option is probably to use the old MPI assembly mode (i.e. the non-Bloom-filter mode) on a large-memory machine.

Sorry for the trouble.

**Comment by benvvalk** [comment]
Increasing `kc` to 4 or 5 may also help.
