### ISSUE TITLE
can I trick Abyss with a Minimap2 alignment file?

### ISSUE THREAD

**Issue by devonorourke** [bcgsc/abyss#227]
I'd love to use Nanopore reads with the the _Long scaffolding_ option within Abyss, but was wondering if there was a way to use an alternative to the bwa aligner. I was motivated from [this old](https://groups.google.com/forum/#!searchin/abyss-users/long%7Csort:date/abyss-users/FtQQPnhBgiU/ZrWbC-lUh1sJ) (2015!) Google Group thread and thought perhaps it would be possible to tweak the existing `abyss-pe` file to switch out the bwa-mem process with Minimap.

I can confirm that adding a Nanopore .fasta file accompanying the `long` parameter in `abyss-pe` worked fine with the default (bwa) aligner (that is, the process completed and no errors were thrown). But if I'm thinking about which aligner is better for working with Nanopore reads, even Heng Li himself [would have advised](http://lh3.github.io/2018/04/02/minimap2-and-the-future-of-bwa) using Minimap2 over bwa...

Ultimately I took the scaffolds.fa file from `abyss-pe` and used it as the reference with which my Nanopore reads were aligned and generated a .sam file. Let's call this one `minimap.sam.gz`...

Can I trick Abyss by substituting this .sam file in place of the one it generated by default (call it `bwa.sam.gz`)? I thought about trying this out, but when I do just this the summary file generated is no different if I leave either .sam file in the working directory with which the `abyss-pe` script is executed.

Maybe there are more upstream files that I need to modify, and perhaps it's not as simple as substituting one .sam file for another?

Thanks for any insights you can offer.

Cheers,
Devon

**Comment by benvvalk** [comment]
Hi @devonorourke, yes I think it should be possible to do exactly what you are proposing -- make your own `sam.gz` file and substitute it into the pipeline.  Since you already generated a file using the default bwa alignment, you know probably know what that filename should be called -- I believe it is `<assembly_name>-8.sam.gz`.

`abyss-pe` is a Makefile script, so you can use all of the normal tricks with `make` to resume the pipeline, build different targets, etc.  In particular, adding `--dry-run` to the end of your `abyss-pe` command is really helpful in these types situations where you want to "trick" `abyss-pe` into doing something non-standard.  (The `--dry-run` option prints the commands that `make` *would* run as a result of your `abyss-pe` command, without actually running them.)

Better out-of-the-box support for scaffolding with nanopore/pacbio reads has been requested/proposed in the past (e.g. #81, #83) but unfortunately we haven't gotten around to addressing that request.  (Nor does it seem likely in the immediate future.)

**Comment by sjackman** [comment]
The software LINKS also from our group may be used to scaffold an ABySS assembly.
See https://github.com/bcgsc/LINKS

**Comment by benvvalk** [comment]
@sjackman Oh right, how could I forget to mention that!? LINKS is a much more mature / well-tested option for long-read scaffolding, IMO.

**Comment by sjackman** [comment]
@devonorourke I'm going to close this issue for now. We'd like to support long read scaffolding directly within ABySS, but it's not a priority for now. We recommend using LINKS.
