### ISSUE TITLE
Sealer Bloom Filters

### ISSUE THREAD

**Issue by schutzekatze** [bcgsc/abyss#239]
Hi,

I did some benchmarking on Sealer and it seems that most of time is wasted loading sequence files and building bloom filters from them. In particular, for every k value, the files are loaded again, which seems unnecessary, as they can be loaded once and then have bloom filters built for every k value. Do you think this is worth optimizing? Also, is there a reason why, by default, Sealer doesn't reuse filters? You need to prebuild them explicitly.

Cheers

**Comment by sjackman** [comment]
To build multiple Bloom filters concurrently, those Bloom filters would need to be able to fit in memory concurrently, which may or may not be the case, but it's an interesting suggestion.
@JustinChu Do you have any tools for building multiple Bloom filters with a single pass through the sequencing data?

> Also, is there a reason why, by default, Sealer doesn't reuse filters?

Typically Sealer is run only once, so there's no need to reused the filters. What's your use case?

**Comment by schutzekatze** [comment]
> Typically Sealer is run only once, so there's no need to reused the filters. What's your use case?

Ah, alright. I'm still exploring the project and thought bloom filter files were generated at some previous pipeline stage as well, and that sealer could reuse them. I'm trying out the mentioned optimization and will post here with results.

**Comment by JustinChu** [comment]
I might, but otherwise it should be easy to implement. The issue might be that konnector (thus sealer) might still use old single hash function bloom filters with cityhash rather than our latest implementation so seed and memory might be an issue. Suffice to say, there is room for optimization of the code.

**Comment by sjackman** [comment]
ABySS has to modes of operation to build the de Bruijn graph. The older implementation uses hash tables. The newer implementation uses Bloom filters. If used in Bloom filter mode, in principle that Bloom filter could be saved and reused. In practice however, the most benefit is expected from Sealer when it is used at values of *k* that are different from the initial assembly, both smaller to resolve coverage gaps, and larger to resolve repeats.

**Comment by schutzekatze** [comment]
So I noticed all Kmers share length with a static length member. Is this to save memory if using a large number of Kmers? It makes it slightly harder to parallelize as it requires that all threads use the same k value at a time.

**Comment by sjackman** [comment]
Yes, it is to reduce memory usage. 32 bytes are required to store a 128-mer using 2 bits per byte. Adding a length member to each *k*-mer would increase that by 8 bytes to 40, a 25% increase. For smaller values of *k* it would be proportionally more.

Rather than having one thread tackle each value of *k*, you may found that it's easier to have all threads co-operate on a single value of *k*, and tackle each value of *k* in succession with all threads.

**Comment by mmokrejs** [comment]
I discussed with Vladimir the possible goals here and it appears the anticipated speedup here would not be that large.

Nevertheless, provided we have a 3TB RAM machine and in hash-based mode abyss needed only up to 1.3TB for k=160 and 800GB for k=128 for the fish 1.3Gbp genome, and provided Bloom filters reduce memory requirements to 1/10, that one could allow to have Bloom filter(s?) in memory at once and even allow the 8Byte overhead. Maybe as an experiment would be still worth some time. Depends on his free time.

**Comment by benvvalk** [comment]
@mmokrejs 

I agree. My recollection is that the majority of the wallclock time is spent on hashing k-mers rather than I/O, in which case building multiple Bloom filters in a single file pass would probably not save much time.

**Comment by JustinChu** [comment]
Theoretically, aside from hitting a cache performance wall, there could be gains to be made if we did more work in parallel. This would most likely be the case if it was a hashing bottleneck. If the limit is due to cache performance then we are out of luck and would need to try things like blocked bloom filters.

At the very least I'm not sure if the current version of sealer uses multiple threads during construction on a single bloom filter. It could be nice to see how well it scales with the number of threads.

**Comment by benvvalk** [comment]
sshh, stalebot.
