### ISSUE TITLE
Error when trying to run abyss-pe

### ISSUE THREAD

**Issue by kokyriakidis** [bcgsc/abyss#244]
I compiled abyss but every time I try to run abyss-pe it shows this error 

```
[kyriakidk@ui3 bin]$ ./abyss-pe
zsh: no such option: pipefail
zsh: no such option: pipefail
zsh: no such option: pipefail
zsh: no such option: pipefail
zsh: no such option: pipefail
zsh: no such option: pipefail
make: *** [error] Error 1
```
How can I fix this?

**Comment by benvvalk** [comment]
Sorry about this, @kokyriakidis.  The error happens because your version of `zsh` is too old and does not support the `pipefail` option.

This will probably be fixed soon.  In the meantime, the easiest fix is to install a recent version `zsh` (using `linuxbrew` for example).

This issue is a dup of #240

**Comment by sjackman** [comment]
To work around this issue, edit the file `abyss-pe` and delete the line…
```sh
SHELL=zsh -e -o pipefail
```
