### ISSUE TITLE
difference between abyss-gapfill and abyss-sealer

### ISSUE THREAD

**Issue by lsterck** [bcgsc/abyss#269]
while looking into using abyss-selaer I also noticed there is an abyss-gapfill program as well in the distribution. What is the difference and should (can) I use the gapfill one as well?

thx in advance

**Comment by benvvalk** [comment]
@lsterck `abyss-gapfill` was a program written back in 2014.  I've never used it and I don't think it has seen very much use in general, as it is not part of the standard ABySS pipeline run by `abyss-pe`.

Looking at the source code, the idea of the program is to align the reads to the assembly scaffolds, look for reads that align across scaffold gaps, then use the read sequence to fill in the gap (i.e. string of consecutive   "N" chars).

If you're looking for alternative gap filling programs, I would recommend trying [RAILS/Cobbler](https://github.com/bcgsc/RAILS) instead (also created by our team). It uses a similar idea to `abyss-gapfill` but seen much heavier use.

**Comment by lsterck** [comment]
alright, thx.

No, I was just looking of the `abyss-sealer` in the bin folder and also saw that one in there as well.
ah, ok, thanks for the pointer. Is that something I should consider as replacement for `abyss-sealer `?

**Comment by lsterck** [comment]
interesting read, so if I understand correctly i can throw in for example some PacBio data as well?

**Comment by lsterck** [comment]
btw, is there any command that I can run the whole pipeline of abyss software? like for instance even up to this abyss-sealer or do I always have to run them independently?

**Comment by benvvalk** [comment]
@lsterck Yes,  exactly. If you have access to long reads (like PacBio) you can potentially close much longer gaps than Sealer could, using RAILS/Cobbler, but the accuracy of filled-in sequence will probably be worse due to the higher error rate  of the long reads.  (Sealer on the other hand works by performing a graph search through the de Bruijn graph to connect the flanking sequences next to a gap.)

Sealer is not part of the automated `abyss-pe`, but that's definitely possible and it would be a nice usability improvement, I agree.

**Comment by sjackman** [comment]
I didn't even know that `abyss-gapfill` existed. I learned something today!

**Comment by lsterck** [comment]
:)
wow, then we all did apparently ;)
