### ISSUE TITLE
Why not modernizing a bit the project?

### ISSUE THREAD

**Issue by lightyear15** [bcgsc/abyss#300]
Your project looks like it might need some refurbishing.
Why not moving to some modern C++ compiler, with some modern C++, like C++14 or even C++17??
It might gain some benefit if we move it to CMake rather than keep using autconf and other older stuff.
Fancy an help?

**Comment by schutzekatze** [comment]
There is some ongoing effort in modernizing parts of ABySS by separating common code into a library. Other than that, while the project would ideally be modernized, it's not our current priority. If you want to contribute, that'd be great, so feel free to open pull request(s). C++14 would probably be better, as I think we want to keep some backwards compatibility.

**Comment by sjackman** [comment]
I'd recommend against code churn for the sake of code churn. It's far too easy to introduce bugs. The ABySS test suite is not terribly strong nor comprehensive. I am definitely in favour of modernizing the code of individual modules when someone is actively working on developing that module. Contributing unit tests would be a fantastic way to contribute to ABySS.

I am strongly against migrating to CMake. autotools is better designed and implemented, and it has better documentation and examples, in my opinion. Newer is not necessarily better.

**Comment by sjackman** [comment]
I should also say, thank you for your interest in ABySS! Though we may have differing opinions, I do value your point of view and discourse. The single most important possible contribution to improve the quality of the ABySS code base would be to measure code coverage of the test suite. We'd welcome a PR to implement that.

**Comment by sjackman** [comment]
I once was but am no longer the lead developer of ABySS, though I was involved with the development of ABySS for a full decade! So though I have my opinions (strongly-held at times), those opinions of the current developers are the final say.

**Comment by lightyear15** [comment]
To be honest, 
I am not really into bio informatics, but I am really into C++ and my intention was to use this relative small project as a "playground" ( don't get me wrong, I am not considering this a toy) to practice some modern C++. 
Nothing too fancy of course, just removing old stuff like pthread, raw pointers, or boost stuff that have been included in std in the last standard revisions, and also applying some general modern C++ best practices.  And if more unit tests were needed in order to get my PRs approved I would write them. 

Regarding CMake, well mate, seems like C++ industry disagrees with you. Out there people are using CMake most of the times. CMake + Ninja makes the compilation way faster than autotools. Anyway that's just my opinion

**Comment by sjackman** [comment]
From a software engineering standpoint, tidying up working legacy code just for tidy sake is unfortunately an anti-pattern. It's worthwhile when there's an end-user reason to be working on the code, and its poor style is holding back developers. Otherwise, there's lots of opportunity to silently break the code, or negatively affect its performance, without realizing it.

It'd be super fantastic if you'd like to start with implementing CI to measure code coverage of unit tests. I'd be much more comfortable accepting aesthetic patches if the code was covered by unit tests. Ideally I'd also like to test for performance regressions, which is a bit trickier. I'm not personally familiar with any out-of-the-box solutions for that.

Regarding CMake, it's based on anecdotal evidence and subjective personal experience. When CMake breaks, it breaks in weird ways, and is difficult to troubleshoot. I like its syntax even less than autotools, which isn't saying much, because the autotools syntax is quite bad.
