### ISSUE TITLE
abyss-fatoagp

### ISSUE THREAD

**Issue by bbista** [bcgsc/abyss#344]
Hello,
abyss-fatoagp gives me an error. Could you please help me figure out what is going wrong?
abyss-fatoagp -f contigs.fasta PUN_polished.fa
Died at /work/LAS/bbista/abyss/bin/abyss-fatoagp line 22, <> line 3.

Just to be clear PUN_polished.fa contains the scaffolds and contigs and I need an agp file and a fasta file for contigs i.e. contigs.fasta

Best,
bbista

**Comment by lcoombe** [comment]
Hi @bbista ,

Based on that error message it seems to be an error in parsing the input fasta file. Is your fasta file single line or multi-line (ie. are sequences all on one line, or are they separated by newlines?). If it is multi-line, try removing the extra line breaks so you have one sequence per line - `seqtk seq` is useful for this.
Otherwise, could you take a look at the third line of your fasta file and ensure that it starts with the expected `>` character?

Thank you for your interest in ABySS!
Lauren

**Comment by bbista** [comment]
Hello @lcoombe,
You are right. The fasta file I am using is multi-line. Once I removed the line breaks the script works perfectly.
Thank you.
Best,
bbista

**Comment by lcoombe** [comment]
Excellent! I'm glad that fixed the issue.
