### ISSUE TITLE
`abyss-pe’: No such file or directory

### ISSUE THREAD

**Issue by azrasid** [bcgsc/abyss#345]
ABYSS 2.2.4

# Assembly error

I am getting this error
error: `abyss-pe’: No such file or directory

I used this simple command. I ran it on our University Cluster
[azra@n12 ~]/opt/exp_soft/bioinf/bin/ABYSS  abyss-pe name=NA12878 -k96 in=‘NA12878_R1.fq  NA12878_R1.fq’ -o scaff78

Please suggest what I am doing wrong.

**Comment by jowong4** [comment]
```
export PATH=/opt/exp_soft/bioinf/bin:$PATH
abyss-pe name=NA12878 -k96 in=‘NA12878_R1.fq NA12878_R1.fq’ -o scaff78
```

Can you try this?

**Comment by azrasid** [comment]
Hi tried suggested command with following error:

[azra@n14 ABYSS]$ abyss-pe name=NA12878 k=96 in='/home/azra/Simulation/genes/cyp2c19/NA12878_R1.fq /home/azra/Simulation/genes/cyp2c19/NA12878_R2.fq' -o scaff78
mpirun -np 1 ABYSS-P -k96 -q3    --coverage-hist=coverage.hist -s NA12878-bubbles.fa  -o NA12878-1.fa /home/azra/Simulation/genes/cyp2c19/NA12878_R1.fq /home/azra/Simulation/genes/cyp2c19/NA12878_R2.fq 
bash: mpirun: command not found
make: *** [NA12878-1.fa] Error 127

**ls /opt/exp_soft/bioinf/bin/ABYS**

[azra@n14 /]$ ls /opt/exp_soft/bioinf/bin/ABYSS 
/opt/exp_soft/bioinf/bin/ABYSS

**Comment by lcoombe** [comment]
@azrasid - Do you have `open-mpi` installed on your system? Looks like it isn't being found.
You could also run ABySS in the Bloom filter de Bruijn graph mode, which is really great because it uses far less memory. To run in that mode, you just have to specify `B`, `H`, `kc` -- more details here: https://github.com/bcgsc/abyss#assembling-using-a-bloom-filter-de-bruijn-graph

**Comment by azrasid** [comment]
Many thanks . 
Working perfectly.
