### ISSUE TITLE
Parameters for fish assemblies

### ISSUE THREAD

**Issue by ms-gx** [bcgsc/abyss#358]
ABySS 2.2.5
Ubuntu 20.04.1 LTS

Genome Size: about 0.8Gbp
Coverage: about 60x
Data: Illumina 150bp paired-end, good quality runs

I have a couple of fish genome assemblies to do. All the fish have undergone the teleost-specific whole genome duplication (see for example here: https://link.springer.com/article/10.1007/s10641-010-9628-7). So they are kind of tetraploid.

I ran GenomeScope 2 on them. Below you can see the result for two.

My questions:
1) Do you have recommendations regarding specific parameters for this type of genomes?
2) What kmer-size do you recommend? I run them with kmer-size 96 like this:
`abyss-pe name=MY_NAMe k=96 in='R1.fastq.gz R2.fastq.gz' j=32 `

Here the genome statistics for one (with k=96, command from above):
```
n	n:500	L50	min	N75	N50	N25	E-size	max	sum	name
1184113	255177	32974	500	2553	5965	11424	8410	109268	728.1e6	BK_2-unitigs.fa
965908	184373	19781	500	4610	10298	19801	15047	231716	758.4e6	BK_2-contigs.fa
939818	161145	13730	500	6302	14617	28536	21454	288317	757e6	BK_2-scaffolds.fa
```

The corresponding GenomeScope 2 run below is the first link.

3) When having only normal PE data but no mate-pairs, would you still use the scaffold-result as the final assembly?
4) If I aim for the haploid assembly, what parametrizations do you recommend?

Here two results from GenomeScope2:
First genome: http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=6Ybjj9aAxGBqz2DgWzKJ
Second genome: http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=nhrxb7o0grKqH0sbK21E

More general questions:
1) Do you have a detailed explanation of the parameters anywhere?
2) What parts of the pipeline are multicore? When I checked `htop` (not all the time) I always saw just one thread running.

**Comment by mmokrejs** [comment]
Hi Michael,
  you are underestimating the genome size. The predcited value depends on the k-mer size used for the k-mer analysis. Compare the following two figures.

[two_k-mer_analyses_of_1.3Gbp_fish_genome.pdf](https://github.com/bcgsc/abyss/files/5752418/two_k-mer_analyses_of_1.3Gbp_fish_genome.pdf)


  Or even, look at the various analyses of the same input data (paired-end and long mate-pair 5kbp Illumina libs, 2x250 reads):

tt_16D1C3L12__PE_MP__ntCard_k32.histo
http://genomescope.org/analysis.php?code=3QqcfvLBKRwDtwi7S2X0

tt_16D1C3L12__PE_MP__ntCard_k64.histo
http://genomescope.org/analysis.php?code=ZFFBghIODiCvk3YTWauj

tt_16D1C3L12__PE_MP__ntCard_k96.histo
http://genomescope.org/analysis.php?code=zzWhjhQLbPrsr71ineYM

tt_16D1C3L12__PE_MP__ntCard_k112.histo
http://genomescope.org/analysis.php?code=L6DbOeQhq3dftKa7iMYK

tt_16D1C3L12__PE_MP__ntCard_k128.histo
http://genomescope.org/analysis.php?code=DS3L6FbjjuFsplV2hjdH

tt_16D1C3L12__PE_MP__ntCard_k144.histo
http://genomescope.org/analysis.php?code=C8RNj53qEnrgcYePakEM

tt_16D1C3L12__PE_MP__ntCard_k156.histo
http://genomescope.org/analysis.php?code=GuewGa4LH8oChATh8ICW


  We had 2x250 Illumina reads, which make a huge difference. 2x150 is not bad but you spend better more money on proper sequencing and obtain a few long mate-pair libraries instead of wasting extra CPU cycles and pushing your bioinformatics efforts to the limits. BTW, our efforts to yield 5kbp and 8kbp long mate-pair libraries resulted in all being more or less 5kbp libraries with just narrower or wider insert-size distribution.

  In the end I used K-mer size 160 and even at k-mer size 192 I could get comparatively good assembly using abyss-2.0.2. I pre-polished the FASTQ reads using ECC correction using tadpole.sh, k=63 (from BBmap bundle). For assembly I tested k-mer sizes 64, 96, 128, 144, 160, 192. The last 3 were all great.

[summary_of_assemblies.pdf](https://github.com/bcgsc/abyss/files/5752468/summary_of_assemblies.pdf)

  Abyss-2.0.2 scaled well (unlike SPAdes at that time) for me using threads, on 112 CPU core server. It easily used 1.9TB of RAM for the basic assembly - note, I did not go the Bloom-filter way, I could have dropped the memory requirement probably to 1/10. I used SGI UV2000 server.

  Single threaded was only abyss-sealer if memory serves me right. That has changed meanwhile. From my old notes I can give you some hint:
```
abyss-sealer
with default settings closed 10.8873% gaps, 106hrs wallclock at 104CPUs, used 3TB RAM, finished
with ‘-B nolimits’ is too slow, mostly single-threaded, cancelled

```


You can see more details on my past efforts and experience here, especially which steps scaled well already at that time:
https://github.com/bcgsc/abyss/issues/187
https://github.com/bcgsc/abyss/issues/220

**Comment by ms-gx** [comment]
@mmokrejs thanks for your comments! We are fully aware that 150bp PE does not result in a state-of-the-art high-quality assembly. If we wanted this, we would anyway combine Illumina with Nanopore as we did in the past already where we got very nice assemblies. But to answer our question for the current species under study, Illumina should be sufficient.

However, I still want to get an ideal assembly, even doing PE 150. I did a sweep of kmer size and was able to optimize quote substantially.

My question regarding single-/multithreaded execution was related to `abyss-pe` only. But I as far as I could see only the mapping parts are multithreaded.

**Comment by sjackman** [comment]
> What parts of the pipeline are multicore? When I checked htop (not all the time) I always saw just one thread running.

At the de Bruijn graph stage
the Bloom filter mode can use multithreading.
the non-Bloom filter mode can be parallelized using Open MPI.

See https://github.com/bcgsc/abyss#assembling-using-a-bloom-filter-de-bruijn-graph
