### ISSUE TITLE
Question about documentation for optimizing k/kc.

### ISSUE THREAD

**Issue by mglubber** [bcgsc/abyss#381]
I have a quick question about the documentation for optimizing k/kc. According [to the README](https://github.com/bcgsc/abyss#optimizing-the-parameters-k-and-kc), you can iterate over both with the following loop:

```
for kc in 2 3; do
	for k in `seq 50 8 90`; do
		mkdir k$k
		abyss-pe -C k$k name=ecoli -B2G k=$k kc=$kc in=../reads.fa
	done
done
```

However, this tries to re-run the assembly with different kc values in the same directory (e.g k72). When I run it I get the following message for `kc>2`:
```
make: Entering directory /blah/blah/k72'
make: Nothing to be done for `default'.
make: Leaving directory `/blah/blah/k72'
```

Should the loop be something like:
```
for kc in 2 3; do
	for k in `seq 50 8 90`; do
		mkdir kc$kc_k$k
		abyss-pe -C kc$kc_k$k name=ecoli -B2G k=$k kc=$kc in=../reads.fa
	done
done
```
Or should abyss-pe be rerunning/updating the assembly with the new kc values, and there's something wrong with my implementation?

**Comment by vlad0x00** [comment]
Hi @mglubber ,

Thanks for using ABySS! You are right, that is an error in the README, there should be separate assemblies/directories for every combination of k and kc. Additionally, I just noticed that the Bloom filter parameter is passed incorrectly in the example, it should be `B=2G` instead of `-B2G`. I'll fix it right away.

**Comment by mglubber** [comment]
Thanks for such a prompt response. Good catch with the the Bloom filter parameter - I ran into issue with that too, and I completely forgot to mention it!
