### ISSUE TITLE
Please add to README how to run tests

### ISSUE THREAD

**Issue by yurivict** [bcgsc/abyss#452]

**Comment by lcoombe** [comment]
Hi @yurivict,

Could you please elaborate a bit on what additional information about testing ABySS you'd like to see in the README?

There are a number of examples of running ABySS in the README currently in the Examples section: https://github.com/bcgsc/abyss#examples

Thank you for your interest in ABySS!
Lauren

**Comment by yurivict** [comment]
I would like to know what command runs the testsuite? Is it ```make test```?

**Comment by lcoombe** [comment]
In order to test your ABySS installation, I strongly encourage following the instructions here: https://github.com/bcgsc/abyss#assemble-a-small-synthetic-data-set 

The compilation tests that we run with our CI: https://github.com/bcgsc/abyss/blob/master/azure-pipelines.yml 

To run the unit tests: `make check`

**Comment by yurivict** [comment]
```make check``` runs tests, thanks!
