### ISSUE TITLE
ABySS singularity container on cluster issue

### ISSUE THREAD

**Issue by zcalamari** [bcgsc/abyss#485]
- ABySS version 2.1.5 (singularity container)
- Rocky Linux release 8.9 (Green Obsidian)

Hello, 

I am receiving an error trying to use ABySS from the bcgsc singularity container in an assembly loop. The genome is mammalian (around 2.5 GB) and we have around 100x short read coverage (reads were combined with Konnector and MergePairs prior to assembly). Konnector and MergePairs ran without issue from the singularity container, and the directory that I've set for TMP definitely exists and should have write permission. I'm not as familiar with using singularity containers, but I have also attempted this with the -B flag to bind directories and with multiple directories that all exist. Any insights into the situation would be appreciated!

**The command line I am running:**

export SINGULARITY_TMPDIR=/expanse/lustre/scratch/calamari/temp_project
export SINGULARITY_LOCALCACHEDIR=/expanse/lustre/scratch/calamari/temp_project

for kc in 2 3 ; do
        for k in `seq 66 8 90`; do
                mkdir k${k}-kc${kc}
                singularity exec /home/calamari/abyss.sif abyss-pe B=200G -C k${k}-kc${kc} k=$k kc=$kc np=128 j=128 \
                name=Ol pe='L1' \
                L1='/expanse/lustre/projects/ccn120/calamari/All_1P.fq.gz /expanse/lustre/projects/ccn120/calamari/All_2P.fq.gz'\
                se='../Kon_pseudoreads.fq ../MP_merged.fastq ../MP_reads_1.fastq ../MP_reads_2.fastq' ;
        done ;
done

**The error I get:**
Building the suffix array...
Building the Burrows-Wheeler transform...
Building the character occurrence table...
sort: cannot create temporary file in '/expanse/lustre/scratch/calamari/temp_project': No such file or directory
error: `L1-3.hist': No such file or directory
make: *** [L1-3.dist] Error 1
make: *** Deleting file 'L1-3.dist'

**Comment by lcoombe** [comment]
Hi @zcalamari,

A few suggestions:
- The latest ABySS singularity images are available on quay.io: https://quay.io/repository/biocontainers/abyss?tab=tags
  - I recommend using the latest ABySS version from there - we don't update the images on dockerhub since these images on quay.io are updated automatically when the conda recipe is updated
- You do generally need to use bindings when using singularity. You should include all the directories that you will need to access using `-B`, including directories where data is located, your working directory, etc. For example, the test command I used was:
```
singularity exec -B /projects/datasets/ecoli/illuminaMiSeq_Fall2014/subsample/60X/:/projects/datasets/ecoli/illuminaMiSeq_Fall2014/subsample/60X,$PWD:$PWD /projects/bin/abyss/2.3.9/abyss_2.3.9--h103dbdd_0.sif abyss-pe B=1G k=75 kc=3 j=24 name=ecoli lib='pelib' pelib="/projects/datasets/ecoli/illuminaMiSeq_Fall2014/subsample/60X/Ecoli_S1_L001_R1_001.60X.fastq.gz /projects/datasets/ecoli/illuminaMiSeq_Fall2014/subsample/60X/Ecoli_S1_L001_R2_001.60X.fastq.gz"
```
- I have 3 singularity variables specified in my `.bashrc`: `SINGULARITY_LOCALCACHEDIR`, `SINGULARITY_CACHEDIR`, `SINGULARITY_TMPDIR`

I hope that helps - thank you for your interest in ABySS!
Lauren

**Comment by zcalamari** [comment]
Thanks, Lauren, I apparently had the bindings specified incorrectly when I tried previously. It seems to be working now! 

Best,
Zac

**Comment by lcoombe** [comment]
Excellent - glad to hear that!
