### ISSUE TITLE
Abyss crashes on aTRAM step

### ISSUE THREAD

**Issue by daisieh** [bcgsc/abyss#66]
I am not sure what is happening, but when I try to assemble the reads found by aTRAM using this command:
```
"/usr/local/bin/abyss-pe k=32 name=/Users/daisie/test/testout.1.blast.fasta_temp  in='/Users/daisie/test/testout.1.blast.fasta_1.fasta /Users/daisie/test/testout.1.blast.fasta_2.fasta'"
```

it always fails with this error:
```
abyss-scaffold   -k32 -s200 -n10 -g /Users/daisie/test/testout.1.blast.fasta_temp-6.path.dot  /Users/daisie/test/testout.1.blast.fasta_temp-6.dot /Users/daisie/test/testout.1.blast.fasta_temp-6.dist.dot >/Users/daisie/test/testout.1.blast.fasta_temp-6.path
error: Expected `igraph' and saw end-of-file
make: *** [/Users/daisie/test/testout.1.blast.fasta_temp-6.path] Error 1
make: *** Deleting file `/Users/daisie/test/testout.1.blast.fasta_temp-6.path'
```

**Comment by benvvalk** [comment]
Hi Daisie,

Sorry, I need a bit more data.  Can you provide the full log output of your ABySS run?  (There may be useful clues in the log output of the upstream steps.)  Also, if possible, please turn on the verbose logging option by adding 'v=-v' to the abyss-pe command.

I suspect that ABySS is failing because the scaffolding algorithm isn't finding any paired end links between contigs, and that is resulting in an empty graph (.dot) file.  Given that you are doing targeted assembly, it may be reasonable to just run the assembler up to the contig stage, in which case you will not get the error anymore. (You can do that by adding the word 'contigs' to the end of the abyss-pe command.)

**Comment by sjackman** [comment]
It looks like one or both of these files is corrupt:
+ `/Users/daisie/test/testout.1.blast.fasta_temp-6.dot`
+ `/Users/daisie/test/testout.1.blast.fasta_temp-6.dist.dot`

**Comment by daisieh** [comment]
That's true, we probably don't need scaffolding. Thanks guys!

**Comment by sjackman** [comment]
Has that resolved your issue then, Daisie? If you don't need scaffolding, you can add `unitigs` to your `abyss-pe` command line to disable contigging/scaffolding with paired-end data.

**Comment by daisieh** [comment]
I'll talk to Julie about it, but I think this does solve it. Thanks!
