### ISSUE TITLE
sort issue?

### ISSUE THREAD

**Issue by macmanes** [bcgsc/abyss#78]
During abyss-map ABySS 1.9.0. Happened twice in a row. 

```
for k in 71; do
    abyss-pe -C k$k np=40 k=$k name=Mya$k l=25 n=5 \
    lib='pe1 pe2' mp1_l=25 mp2_l=25  \
    mp='mp1 mp2' long='long1 long2' v=-vv \
    pe1='/mouse/Mya/hcgs_reads/pe/clam300.P2_1P.fq.gz /mouse/Mya/hcgs_reads/pe/clam300.P2_2P.fq.gz' \
    pe2='/mouse/Mya/nygc_reads/pe/clam500.P2_1P.fq.gz /mouse/Mya/nygc_reads/pe/clam500.P2_2P.fq.gz' \
    mp1='/mouse/Mya/nygc_reads/mp/clam5kb_1.fastq /mouse/Mya/nygc_reads/mp/clam5kb_2.fastq' \
    mp2='/mouse/Mya/nygc_reads/mp/clam10kb_1.fastq /mouse/Mya/nygc_reads/mp/clam10kb_2.fastq' \
    long1='/mouse/Mya/output_lsc/corrected_LR.fa' \
    long2='/mnt/data3/macmanes/Mya/clam.Trinity.fasta';
done
```

```
...
Read 960000000 alignments. Hash load: 2 / 64 = 0.03125 using 684 kB.
Mapped 950214599 of 960893486 reads (98.9%)
Mapped 886584796 of 960893486 reads uniquely (92.3%)
Read 960893486 alignments
Mateless           0
Unaligned    4617093  0.961%
Singleton    1444701  0.301%
FR         179799914  37.4%
RF             22474  0.00468%
FF             84225  0.0175%
Different  294478336  61.3%
Total      480446743
FR Stats mean: 213.6 median: 217 sd: 28.59 n: 179782003 min: 21 max: 351 ignored: 40385
                               ___▁▃▅▆███▇▅▃▂__
Mate orientation FR: 179799914 (100%) RF: 22474 (0.0125%)
The library pe1-3.hist is oriented forward-reverse (FR).
Stats mean: 213.6 median: 217 sd: 28.59 n: 179782003 min: 21 max: 351
                               ___▁▃▅▆███▇▅▃▂__
Minimum and maximum distance are set to -70 and 351 bp.
error: input must be sorted: saw `0:525499' before `0:315612'
make: *** [pe1-3.dist] Error 1
make: *** Deleting file `pe1-3.dist'
```

**Comment by benvvalk** [comment]
Hi Matt,

The ABySS pipeline assumes numeric IDs for the contigs.  My guess would be that you are getting the error because you are doing the de Bruijn assembly with an external tool and then feeding the result into ABySS for the contig/scaffold stages.  Is that a correct guess? There is nothing wrong with that idea, but you will have to rename the IDs in your file.  I find `bioawk` is a pretty handy tool for that, e.g.

```
$ bioawk -c fastx '{print ">"i++; print $seq}' orig.fasta > renamed-ids.fasta
```

**Comment by macmanes** [comment]
Nope, this is all ABySS.. 

```
head Mya71-3.fa

>0:1 72 757
AATATAAAGGACCAATACTATGCGTGCAGTTGTTTTCCCAGTGATACATGATAAGAGCCTCCTTCATATCTG
>0:5 73 6710
AGAGTGTAAGACCCATCTCCCTTCATAAGAATTGATAATCATCACTGTATTAAATCAAGAAATTGAAACGTAA
>0:6 82 327
TGACGAATAATTGTTTAATATAATTAGACGGCAGGCTATGATGAGATTCATACAATTATTTACATGTTAAATACTACTGTTT
>0:10 82 335
GCATAAAACAGTAAATATATCATTGTTTTAGAAGATCAGGCATGCTTAATGCTTTGAAATAGCTGACTGCTTTATCGACGCT
```

**Comment by benvvalk** [comment]
Egads, I'm not sure how that's even possible!

Do the IDs in Mya71-1.fa and Mya71-2.fa also have `:` in them?  I'm really confused.

**Comment by macmanes** [comment]
oh darn.. I know what the issue is... #holdsheadinshame

The assembly was accidentally killed while it was concatenating all the `contigs-*.fa` files to Mya71-1.fa. I  did not recognize that the fasta defline was different, so I just concatenated all the reads files together and away I went.. Easy enough to get rid of those `:`'s.. Sorry for wasting your time on this one...

**Comment by benvvalk** [comment]
No problem, thanks for letting me know!

**Comment by sjackman** [comment]
The entire pipeline can handle arbitrary non-numeric contig identifiers except for the [`sort` command](https://github.com/bcgsc/abyss/blob/master/bin/abyss-pe#L509) here and other places. Possible solutions are
1. 0-pad the prefixes of contig IDs so that numeric sort and string sort are identical. I like this solution
2. Use `samtools sort` or a similar tool rather than `sort`. Adds a dependency.
3. Implement `abyss-sort`

**Comment by sjackman** [comment]
It could be a good opportunity to replace the quick sort / merge sort with a fast radix sort like DALIGNER.

**Comment by benvvalk** [comment]
Good ideas.  Thanks, Shaun!
