### ISSUE TITLE
abyss-sealer v1.9.0 fails to run to completion

### ISSUE THREAD

**Issue by dparks1134** [bcgsc/abyss#79]
Hello,

I have a number of assembled metagenomes I am running through abyss-sealer. The majority of these finish without issue in ~6 hours. However, a small subset never appear to complete. I have allowed these to run for 100+ hours at this point without completion. The offending metagenomes are ~1/3 lane of Illumina, and are similar in both number of assembled contigs and raw reads as the metagenomes that finish. Furthermore, I can see that abyss-sealer is running successfully for larger k values (k>=50), but getting 'hung' on k=40. I suspect there is an infinite loop in the code.

Have you experienced this problem? Do you have any suggestions on why some metagenomes may take excessive computation time for specific k values?

Cheers,
Donovn

**Comment by benvvalk** [comment]
Hi Donovan,

Yes, I have seen that behaviour unfortunately.

I believe it is not an infinite loop but searches in really dense regions of the graph that cause problems.  At the moment, all that can be done is to adjust parameters to get a more reasonable runtime. The parameters that you could change are (in order of biggest effect to smallest effect):
* `--kmer`,`-k` (increase to make it run faster (as you have already observed))
* `--max-frag`, `-F` (limits search depth, i.e. maximum gap size; decrease to make it run faster)
* `--max-branches`,`-B` (search is aborted when breadth of search frontier exceeds this limit; decrease to make it run faster)

I do believe that this problem is fixable by making adjustments to the search algorithm, but a fix is not imminent.

**Comment by benvvalk** [comment]
Multithreading (`-j`) helps a great deal too, of course, but you are probably already using that.

**Comment by dparks1134** [comment]
Thanks. Changing the maximum gap size (<code>-F</code>) had a huge impact on the running time.

**Comment by benvvalk** [comment]
Glad to hear!

Just a note: I wasn't precise in my response above: -F is actually max_gap_size + 2*flank_length, where flank_length (-L) is 100 bp by default.

**Comment by dparks1134** [comment]
Thanks! Good to know.

**Comment by sjackman** [comment]
Hi, Ben. As this issue is blocking #80, I'm going to reopen it. What can we do to limit the runtime of Sealer to something reasonable even for worst-case data?

**Comment by benvvalk** [comment]
Fixed in [ABySS-2.1.2](https://github.com/bcgsc/abyss/releases/tag/2.1.2).
